# Generated by Django 3.0.3 on 2020-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Jack', max_length=30, unique=True),
        ),
    ]
