language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - staging

before_install:
  - export PATH=$PATH:geckodriver
  - echo $PATH

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pureBeurre.settings.travis

script:
  - ./manage.py test
