dist: bionic
language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - staging
addons:
  firefox: latest

before_script:
  - install-webdrivers

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=config.settings.travis

script:
  - ./manage.py test 
