dist: bionic
language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - master
addons:
  firefox: latest

before_script:
  - install-webdrivers

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pureBeurre.settings.travis

script:
  - ./manage.py test test.test_us
