dist: bionic
language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - staging
addons:
  firefox: latest

# before_install:
#   - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
#   - mkdir geckodriver
#   - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
#   - export PATH=$PATH:$PWD/geckodriver
#   - firefox -v
before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers
# before_script:
#   - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pureBeurre.settings.travis

script:
  - ./manage.py test test.test_us

after_success:
  - echo 'tests réussis, je push sur master'
  - git push origin master