# Generated by Django 3.0.3 on 2020-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200313_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
