# Generated by Django 3.0.3 on 2020-04-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200325_1616'),
        ('user', '0004_profile_mail_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favlist',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
