# Generated by Django 3.0.3 on 2020-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_favlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
