# Generated by Django 3.0.3 on 2020-04-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200408_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail_confirm_sent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mail_confirmed',
        ),
    ]
