# Generated by Django 3.0.3 on 2020-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200609_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mail_confirm_sent',
        ),
        migrations.AddField(
            model_name='profile',
            name='wait_confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
