# Generated by Django 3.0.3 on 2020-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_maj',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_maj',
            field=models.DateField(auto_now=True),
        ),
    ]
