# Generated by Django 3.0.3 on 2020-03-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200319_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='last_maj',
        ),
    ]
