# Generated by Django 3.0.3 on 2020-03-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_last_maj_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_maj',
            new_name='last_maj_0',
        ),
    ]
