# Generated by Django 3.0.3 on 2020-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200319_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='needed',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
