# Generated by Django 3.0.3 on 2020-04-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200325_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='last_maj_0',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_maj_0',
        ),
    ]
