# Generated by Django 3.0.3 on 2020-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200410_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_nutrition_url',
            field=models.CharField(default='pas de repère nutritionnel', max_length=200),
        ),
    ]
