# Generated by Django 3.0.3 on 2020-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_image_nutrition_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_nutrition_url',
            field=models.CharField(default='pas de repères nutritionnels', max_length=200),
        ),
    ]
